apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: food-detection-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-food-detection
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
