apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api-auth
spec:
  selector:
    matchLabels:
      app: api-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
      - name: api-auth
        image: 862980326144.dkr.ecr.us-east-1.amazonaws.com/api_auth:dev-18
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 5008
