apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: food-segmentation-demo-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-food-segmentation-demo
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
