apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-3rd-parties-api
spec:
  selector:
    matchLabels:
      app: 3rd-parties-api
  replicas: 1
  template:
    metadata:
      labels:
        app: 3rd-parties-api
    spec:
      containers:
      - name: 3rd-parties-api
        image: 862980326144.dkr.ecr.us-east-1.amazonaws.com/3rd-parties-api:dev-62
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
        ports:
        - containerPort: 5001
