apiVersion: batch/v1
kind: CronJob
metadata:
  name: images
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: images
            image: 862980326144.dkr.ecr.us-east-1.amazonaws.com/api_images:dev-56
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure